Adopt Terms and Definitions to IEC63278-1:2023
admin-shell-io/aas-specs-api pull request #227
Opened 2024-02-15 16:19 UTC by BirgitBoss

Adoption of Terms and Definitions to IEC63278-1:2023. See changelog for changed terms.
Minor changes w.r.t. abbreviations.

Formatting issues in profile and parameter files fixed.

2024-02-19 16:46 UTC, sebbader-sap requested changes

2024-02-19 16:46 UTC, sebbader-sap commented on documentation/IDTA-01002-3/modules/ROOT/images/SequenceDiagram_1_http.svg
Regarding the note in the bottom-right corner: I think the client is aware that he is either calling a Submodel Service (URL path ends with /submodel) or a Submodel Repository (no .../submodel)

2024-02-19 16:46 UTC, sebbader-sap commented on documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_ServiceSpecifications_Profiles.adoc
> +|AssetAdministrationShellServiceSpecification/SSP-002 |Only read operations; is included in the profile Registry/SSP-001.
```suggestion
|AssetAdministrationShellServiceSpecification/SSP-002 |Only read operations; is included in the profile AssetAdministrationShellServiceSpecification/SSP-001.
```

2024-02-19 16:46 UTC, sebbader-sap commented
@BirgitBoss please have a look at my suggested change above. Rest looks fine.

2024-02-20 08:24 UTC, BirgitBoss commented on documentation/IDTA-01002-3/modules/ROOT/images/SequenceDiagram_1_http.svg
No, the client is not since he or she is justing using the endpoint of the SubmodelDescriptor

2024-02-20 08:47 UTC, sebbader-sap approved these changes

2024-02-20 09:32 UTC, sebbader-sap approved these changes

2024-02-20 09:33 UTC, merged