Update Change Log
admin-shell-io/aas-specs-api pull request #248
Opened 2024-02-29 15:09 UTC by sebbader-sap

Adds the Change Log updates from the V3.0.2 Draft also into the V3.1_prep branch.

2024-03-04 12:23 UTC, BirgitBoss commented on documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_ChangeLog.adoc
> +
```suggestion
* Remove "Level" parameter from API-operations with Format content "Metadata"
```

2024-03-04 12:25 UTC, BirgitBoss commented on documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_ChangeLog.adoc
> +- Fix links in Clause 12.1
```suggestion
* Fix links in Clause 12.1
```

2024-03-04 12:25 UTC, BirgitBoss commented on documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_ChangeLog.adoc
> +- ServiceSpecificationProfileEnum: Corrected explanations for Submodel Repository profile entries
```suggestion
* ServiceSpecificationProfileEnum: Corrected explanations for Submodel Repository profile entries
```

2024-03-04 12:25 UTC, BirgitBoss commented on documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_ChangeLog.adoc
> +- Correct Note 1 in Clause 12.4: "[…] IdshortPaths are base64url-encoded […]" to "[…] IdshortPaths are url-encoded […]"
```suggestion
* Correct Note 1 in Clause 12.4: "[…] IdshortPaths are base64url-encoded […]" to "[…] IdshortPaths are url-encoded […]"
```

2024-03-04 12:25 UTC, BirgitBoss commented on documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_ChangeLog.adoc
> +- Clause 12.2: Correct example for GetAllAssetAdministrationShellIdsByAssetLink
```suggestion
* Clause 12.2: Correct example for GetAllAssetAdministrationShellIdsByAssetLink
```

2024-03-04 12:27 UTC, BirgitBoss commented on documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_ChangeLog.adoc
> +* Change the values for the ServiceDescription class from enum to a list in the OpenAPI definition for the Part 2 classes.
missing in the table below: which API-operations are affected?

2024-03-04 12:28 UTC, BirgitBoss requested changes
one major change was missing it seems to me + table of API-operations was not complete

+ minor editorial issues

2024-03-04 12:31 UTC, BirgitBoss commented on documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_ChangeLog.adoc
> +* Change the values for the ServiceDescription class from enum to a list in the OpenAPI definition for the Part 2 classes.
```suggestion
* Change the values for the ServiceDescription class from enum to a list of strings in the OpenAPI definition for the Part 2 classes.
```

2024-03-22 16:09 UTC, sebbader-sap commented
> one major change was missing it seems to me + table of API-operations was not complete
> 
> * minor editorial issues

Took me some time to understand what you meant. I think I have it now, please check again. Editorial Changes section is now in the "Minor Changes" right at the beginning.

2024-03-26 09:26 UTC, BirgitBoss approved these changes

2024-03-26 09:26 UTC, merged