Extend the Description of the AssetLink Request
admin-shell-io/aas-specs-api pull request #293
Opened 2024-07-03 15:47 UTC by sebbader-sap

2024-07-06 16:52 UTC, BirgitBoss commented on DiscoveryServiceSpecification/V3.0_SSP-001.yaml
> +        description: A list of asset identifiers in the form of an AssetLink. One AssetLink may either represent tehn name/value pair of a SpecificAssetId or the globalAssetId of the asset represente
```suggestion
        description: A list of asset identifiers in the form of an AssetLink. One AssetLink may either represent the name/value pair of a SpecificAssetId or the globalAssetId of the asset represented by the Asset Administration Shell.
```

2024-07-06 16:52 UTC, BirgitBoss commented on DiscoveryServiceSpecification/V3.0_SSP-001.yaml
> +        description: A list of asset identifiers in the form of an AssetLink. One AssetLink may either represent tehn name/value pair of a SpecificAssetId or the globalAssetId of the asset represente
Typo

2024-07-06 16:53 UTC, BirgitBoss requested changes
Correct typos

2024-07-26 15:08 UTC, sebbader-sap commented
@BirgitBoss typo is corrected, please check again.

2024-07-26 15:24 UTC, BirgitBoss approved these changes

2024-08-02 10:03 UTC, merged